### ISSUE TITLE
CloudFlare issues: server is not accessible (Urgent - Daynis)

### ISSUE THREAD

**Issue by daynis-olman** [smart-clean/sc-mobile-backend#6]
CloudFlare issues: server is not accessible (Urgent - Daynis)

**Comment by raj-smartclean** [comment]
Is there issue with our end?

**Comment by daynis-olman** [comment]
Hi Raj,

Attached here are last 100 lines for server logs. 
[TailLogs-1544577555273.txt](https://github.com/smart-clean/sc-mobile-backend/files/2670134/TailLogs-1544577555273.txt)

It seems like you default directory is still **'/var/www/html/'** 
we will need **'/var/app/current/'** 

This is the only issue i can see at the moment!

I am looking further to resolve any more issues as we speak!

Thanks, 
Daynis

**Comment by raj-smartclean** [comment]
Hi, Thanks for your appreciation, I will talk with developer as well to look into this as soon as possible, he is building another Dashboard so later that will be merged to it soon,

**Comment by daynis-olman** [comment]
Thanks Raj. 
We are also looking on our end right now.. will attempt to normalise the environment over the next little while as it seems to be inaccessible at the moment. 

Thanks, 
D.

**Comment by daynis-olman** [comment]
This issue has been resolved. I have modified load balancer security group to allow outgoing traffic for HTTPS and HTTP which has solved the timeout's issue. Closing this down now.
