### ISSUE TITLE
Force SSL redirect for all non-https:// traffic to scportal.com.au

### ISSUE THREAD

**Issue by daynis-olman** [smart-clean/sc-mobile-backend#9]
Hi Raj,

@raj-smartclean 

Should all http:// traffic be redirected to https:// automatically for the http://scportal.com.au ? 
Please let me know if this change is required, as currently we are accepting and serving the page through both protocols. 

Thanks, 
Daynis

**Comment by raj-smartclean** [comment]
Hi Danis, i think, we already getting traffic with https:// so no need to change anything at this moment
